### ISSUE TITLE
Fail to upload snapshot to nextcloud (HTTPError: Response code 504 (Gateway Time-out)) !

### ISSUE THREAD

**Issue by thundergreen** [Sebclem/hassio-nextcloud-backup#65]
**Describe the bug**
Pushing Backup to NextCloud Server ends up in timeout.
**To Reproduce**
make a backup... push ... timeout ...
**Expected behavior**
no timeout
**System information**
- Home Assistant Version : 
- Home Assistant Supervisor Version :
- Nextcloud Version : 
- Addon version : 
- If any, reverse proxy in front Nextcloud : 
Running Nexcloud behind nginx (Docker) 

```
#version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
#    labels:
#      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: nextcloud-letsencrypt
#    depends_on:
#      - proxy
#    networks:
#      - nextcloud_network
#    volumes:
#      - ./proxy/certs:/etc/nginx/certs:rw
#      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
#      - ./proxy/html:/usr/share/nginx/html:rw
#      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=%%LogMeIn%%
      - MYSQL_PASSWORD=%%LogMeIn%%
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
 #     - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
      - /media/thundergreen/Storage:/storage
      - /media/thundergreen/Storage/Docker/NextCloud/php/timeout.ini:/usr/local/                                                                                                                                                             etc/php/conf.d/timeout.ini
    environment:
      - VIRTUAL_HOST=cloud-space.ddns.net
#      - LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
#      - LETSENCRYPT_EMAIL=YOUR-EMAIL
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:

```
**Additional context**
tried to increse timeout by mapping gninx (placed in vhost.d) and php config but apparently not the good config?

nginx extra config (cloud-space.ddns.net):

```
client_max_body_size        10G;
client_body_buffer_size     400M;
fastcgi_read_timeout 2000s;
fastcgi_send_timeout 2000s;
```

php extra config (timeout.ini):

```
php_value upload_max_filesize 16G
php_value post_max_size 16G
php_value max_input_time 3600
php_value max_execution_time 3600
request_terminate_timeout = 900
```
Do you have an example / idea how to get rid of timeout and what config to use here?
